function G = threeLinkUr5e_gravity_vector(g,Q)
%threeLinkUr5e_gravity_vector
%    G = threeLinkUr5e_gravity_vector(g,Q)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    25-Jan-2024 16:02:05
q_2 = Q(2); q_3 = Q(3);
t2 = cos(q_2);
t3 = cos(q_3);
t4 = sin(q_2);
t5 = sin(q_3);
t6 = t3.*3.922e-1;
t7 = t5.*3.922e-1;
t8 = t4.*t5.*(1.19e+2./1.0e+3);
t9 = t3.*1.634e-2;
t11 = t5.*1.634e-2;
t10 = -t7;
t13 = -t4.*(t7-t9);
t12 = t9+t10;
G = [0.0;g.*t2.*(-1.712325)+g.*(t8-t2.*(t3.*(1.19e+2./1.0e+3)+1.7e+1./4.0e+1)).*2.846-g.*(t13+t2.*(t6+t11+1.7e+1./4.0e+1)).*(6.07e+2./2.0e+2);g.*(t13+t2.*(t6+t11)).*(-6.07e+2./2.0e+2)+g.*(t8-t2.*t3.*(1.19e+2./1.0e+3)).*2.846];
